# Generated by Django 4.0.1 on 2022-01-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='date_filmed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='genre',
            field=models.CharField(choices=[('Detective', 'Detective'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romantic', 'Romantic'), ('Anime', 'Anime')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
