# Generated by Django 4.0.1 on 2022-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_tvshow_date_filmed_alter_tvshow_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
